### PR TITLE
compat: Fix mysql support

### LINKED ISSUE #432: Incompatible with mysql
We are currently using a `TextField` with `unique=True` at https://github.com/wncc/instiapp-api/blob/04dfca352d390638d88bb1860a40a25d99a9f3ff/users/models.py#L93

This is incompatible with mysql, so we need to find a way to fix this along with migrating the existing data.

#431

### PR DESCRIPTION
**Pull request by pulsejet**
Fix #432

### CODE REVIEW

**Comment by pulsejet** [comment]
@e-aakash this one is a bit messy
* https://github.com/wncc/instiapp-api/pull/431/commits/f2bcb80b70e6f2633d15265f3bad4975ecf5ba44 - Base64 image upload was silently deprecated a long time ago, and no frontend implementation uses it in my knowledge. Removing this is a good step as `drf_extra_fields` depends on `psycopg2`, if we want a database-agnostic dependency tree.
* https://github.com/wncc/instiapp-api/pull/431/commits/c513051b40a26d6cd6999978b9feef8e5d532194 - follows up on the previous commit and removes the `drf_extra_fields` and `psycopg2-binary` dependencies. This makes it possible to run/test on Windows without installing postgres.
* https://github.com/wncc/instiapp-api/pull/431/commits/79a2eaaf31425c82d965af80044b8f4b50bf2679 - add the test for mysql
* https://github.com/wncc/instiapp-api/pull/431/commits/3ad9aecb9abe9ac17376ed51df7ae6b35b5937f7 - Fix the usage of a unique TextField that mysql doesn't support (and is horrible anyway). Instead, store a hash of the endpoint by overriding `save` for the model, and enforce uniqueness for the hash instead. The custom migrations _should_ take care of existing data, but better test this thoroughly if/before going to prod.
* https://github.com/wncc/instiapp-api/pull/431/commits/75a205fd9296234a24ccc932766402a239f5286d - bump coverage back to 100% =P

**Comment by pulsejet** [comment]
The last two commits should definitely not have been required. Report to Django if you can figure out why maybe.

@e-aakash

**Comment by e-aakash** [comment]
Great work experimenting and getting this work on MySQL. The migrations are finally happening without any errors. ❤️ 
will merge after trying data migration.

On the issue part, I will try to create a small reproducible example giving the same error, and try to figure out if its intended behavior that we misunderstood, or Django error.

**Comment by pulsejet** [comment]
By the way, suggest to merge this even if not migrating to mysql for the sake of (much) easier windows development

**Review by e-aakash — APPROVED** [review]
Great work (as usual 😄)!

**Pull request merged**
